### ISSUE TITLE
wizard in flexform does not work

### ISSUE THREAD

**Issue by EnzephaloN** [FriendsOfTYPO3/mediace#21]
If plugin of type "media" is selected and you're trying to add an audio file by clicking on the link-wizard-button an error appears: Module wizard_link_browser is not configured.
The error appears at "fallback-url" and at "source path"!

Best regards
Johannes

**Comment by HaraldDolderer** [comment]
I can confirm this. mediace is broken in TYPO3 7.6.2

best regards
Harald

**Comment by ghost** [comment]
Same here

**Comment by ghost** [comment]
![mediace-wizzard_link_browser-error](https://cloud.githubusercontent.com/assets/8021910/13570903/8ed6eb12-e471-11e5-9b29-f15f105566f1.png)

Same in TYPO3 7.6.4

**Comment by Diologenes** [comment]
Same problem here...
Could the author of this extension fix it?

Just edit: 
Configuration/FlexForms/media.xml

This is is currently used:
`
<module type="array">
<name>wizard_link_browser</name>
<urlParameters type="array">
<act>file</act>
</urlParameters>
</module>
`

This works for me:
`
<module type="array">
<name>wizard_element_browser</name>
<urlParameters type="array">
<mode>wizard</mode>
<act>file</act>
</urlParameters>
</module>
`

**Comment by Kephson** [comment]
for me (TYPO3 7.6.14) it works with my version see fork https://github.com/Kephson/mediace

**Comment by bmack** [comment]
Can you please check if latest master works? Then I'd tag a new version and push it to TER. Thanks.

**Comment by HaraldDolderer** [comment]
checked! It works.
TYPO3 7.6.15 css_styled_content 
Thanks.

**Comment by DasOni81** [comment]
Can confirm HaraldDolderers info.
On TYPO3 7.6.15 it works with your latest changes for me too.
Thanks for your changes!

**Comment by marclindemann** [comment]
If You select an file via file browser the form gets for example this value for mmFile: "file:231319" after saving the value is lost - when you type it by your own it´s working. But this is maybe a core bug? https://forge.typo3.org/issues/76410

**Comment by bmack** [comment]
We fixed this and just released 7.6.4 (also to packagist and TER).
